# action.yml
name: 'diagrams-action'
author: "Diego Castillo @diegotony"
description: 'Convert python diagrams file to .png'
inputs:
  args:  # id of input
    description: 'diagram python file name'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.diagram-python }}