# action.yml
name: 'diagrams-action'
author: "Diego Castillo @diegotony"
description: 'Convert python diagrams file to .png'
inputs:
  args:  # id of input
    description: 'command to execute python file'
    required: false
    default: python3 diagrams.py

runs:
  using: 'docker'
  image: 'Dockerfile'