# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  diagram-python:  # id of input
    description: 'diagram python file name'
    required: true
    default: 'diagram.py'
outputs:
  image: # id of output
    description: 'image generated'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.diagram-python }}